version: '3'

# Build with docker-compose up
services:
  php:
    build: php
    container_name: appcoin_php
    ports:
      - "9000:9000"
    volumes:
      - ../..:/var/www

  nginx:
    image: nginx
    container_name: appcoin_web
    ports:
      - "8000:80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "../..:/var/www"
    links:
      - php

  mysql:
    image: mysql
    container_name: appcoin_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'appcoin'
    volumes:
      - "./mysql/db:/var/lib/mysql"
    links:
      - php